"""add other ordering models

Revision ID: c55fc4be4e1c
Revises: fe78a61fc4f1
Create Date: 2024-11-03 15:35:55.266627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c55fc4be4e1c'
down_revision: Union[str, None] = 'fe78a61fc4f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('CategoryID', sa.Integer(), nullable=False),
    sa.Column('CategoryName', sa.String(), nullable=True),
    sa.Column('Description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('CategoryID')
    )
    op.create_table('employees',
    sa.Column('EmployeeID', sa.Integer(), nullable=False),
    sa.Column('LastName', sa.String(), nullable=True),
    sa.Column('FirstName', sa.String(), nullable=True),
    sa.Column('BirthDate', sa.String(), nullable=True),
    sa.Column('Photo', sa.String(), nullable=True),
    sa.Column('Notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('EmployeeID')
    )
    op.create_table('shippers',
    sa.Column('ShipperID', sa.Integer(), nullable=False),
    sa.Column('ShipperName', sa.String(), nullable=True),
    sa.Column('Phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ShipperID')
    )
    op.create_table('suppliers',
    sa.Column('SupplierID', sa.Integer(), nullable=False),
    sa.Column('SupplierName', sa.String(), nullable=True),
    sa.Column('ContactName', sa.String(), nullable=True),
    sa.Column('Address', sa.String(), nullable=True),
    sa.Column('City', sa.String(), nullable=True),
    sa.Column('PostalCode', sa.String(), nullable=True),
    sa.Column('Country', sa.String(), nullable=True),
    sa.Column('Phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('SupplierID')
    )
    op.create_table('orders',
    sa.Column('OrderID', sa.Integer(), nullable=False),
    sa.Column('CustomerID', sa.Integer(), nullable=False),
    sa.Column('EmployeeID', sa.Integer(), nullable=False),
    sa.Column('OrderDate', sa.String(), nullable=True),
    sa.Column('ShipperID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['CustomerID'], ['customers.CustomerID'], ),
    sa.ForeignKeyConstraint(['EmployeeID'], ['employees.EmployeeID'], ),
    sa.ForeignKeyConstraint(['ShipperID'], ['shippers.ShipperID'], ),
    sa.PrimaryKeyConstraint('OrderID')
    )
    op.create_table('products',
    sa.Column('ProductID', sa.Integer(), nullable=False),
    sa.Column('ProductName', sa.String(), nullable=True),
    sa.Column('SupplierID', sa.Integer(), nullable=False),
    sa.Column('CategoryID', sa.Integer(), nullable=False),
    sa.Column('Unit', sa.String(), nullable=True),
    sa.Column('Price', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['CategoryID'], ['categories.CategoryID'], ),
    sa.ForeignKeyConstraint(['SupplierID'], ['suppliers.SupplierID'], ),
    sa.PrimaryKeyConstraint('ProductID')
    )
    op.create_table('orderdetails',
    sa.Column('OrderDetailID', sa.Integer(), nullable=False),
    sa.Column('OrderID', sa.Integer(), nullable=False),
    sa.Column('ProductID', sa.Integer(), nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['OrderID'], ['orders.OrderID'], ),
    sa.ForeignKeyConstraint(['ProductID'], ['products.ProductID'], ),
    sa.PrimaryKeyConstraint('OrderDetailID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orderdetails')
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_table('suppliers')
    op.drop_table('shippers')
    op.drop_table('employees')
    op.drop_table('categories')
    # ### end Alembic commands ###
