"""create customer table

Revision ID: fe78a61fc4f1
Revises: 
Create Date: 2024-11-03 14:42:45.799272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe78a61fc4f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('CustomerID', sa.Integer(), nullable=False, primary_key=True, autoincrement=True),
    sa.Column('CustomerName', sa.String(), nullable=True),
    sa.Column('ContactName', sa.String(), nullable=True),
    sa.Column('Address', sa.String(), nullable=True),
    sa.Column('City', sa.String(), nullable=True),
    sa.Column('PostalCode', sa.String(), nullable=True),
    sa.Column('Country', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('CustomerID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers')
    # ### end Alembic commands ###
